apiVersion: v1
kind: Service
metadata:
  name: stadium-office1-mqtt-service
  labels:
    app: stadium-office1-mqtt
spec:
  ports:
  - port: 1883
    protocol: TCP
  selector:
    app: stadium-office1-mqtt

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stadium-office1-mqtt
  labels:
     app: stadium-office1-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium-office1-mqtt
  template:
    metadata:
      labels:
        app: stadium-office1-mqtt
    spec:
      enableServiceLinks: false
      containers:
        - name: stadium-office1-mqtt
          image: eclipse-mosquitto:1.5.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
          env:
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
          securityContext:
            runAsUser: 1883
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - master


---

