apiVersion: apps/v1
kind: Deployment
metadata:
  name: stadium-office1-mqtt2db
  labels:
     app: stadium-office1-mqtt2db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium-office1-mqtt2db
  template:
    metadata:
      labels:
        app: stadium-office1-mqtt2db
    spec:
      enableServiceLinks: false
      containers:
        - name: stadium-office1-mqtt2db
          image: aividtechvision/smtc_mqtt2db:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OFFICE
              value: "37.39856,-121.94866"
            - name: DBHOST
              value: "http://db-service:9200"
            - name: MQTTHOST
              value: "stadium-office1-mqtt-service"
            - name: SCENARIO
              value: "stadium"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - master


---

