---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stadium-office1-analytics-queue
  labels:
     app: stadium-office1-analytics-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium-office1-analytics-queue
  template:
    metadata:
      labels:
        app: stadium-office1-analytics-queue
    spec:
      enableServiceLinks: false
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: stadium-office1-analytics-queue
          image: aividtechvision/smtc_analytics_queue_xeon_gst:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OFFICE
              value: "37.39856,-121.94866"
            - name: DBHOST
              value: "http://db-service:9200"
            - name: MQTTHOST
              value: "stadium-office1-mqtt-service"
            - name: STHOST
              value: "http://stadium-office1-storage-service:8080/api/upload"
            - name: MQTT_TOPIC
              value: "analytics"
            - name: EVERY_NTH_FRAME
              value: "6"
            - name: SCENARIO
              value: "stadium"
            - name: NETWORK_PREFERENCE
              value: "{\"CPU\":\"INT8,FP32\"}"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
            - mountPath: /tmp/rec
              name: recording
      initContainers:
            - image: busybox:latest
              imagePullPolicy: IfNotPresent
              name: init
              command: ["/bin/chown","0:0","/tmp/rec"]
              volumeMounts:
                - mountPath: /tmp/rec
                  name: recording
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
          - name: recording
            emptyDir:
              medium: Memory
              sizeLimit: 150Mi
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - master


---
