#!bin/bash
ssh-keygen -f "/root/.ssh/known_hosts" -R "$1"
# docker save aividtech/smtc_storage_manager:2.0 | sshpass -p "$2" ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_sensor_srs:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_sensor_simulation:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_rtmp_discovery:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_onvif_discovery:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_smart_upload:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_db_init:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_alert:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_api_gateway:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_web_cloud:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_sensor_webrtc:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_object_tracking:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_analytics_object_xeon_gst:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_mqtt2db:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_analytics_entrance_xeon_gst:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_analytics_crowd_xeon_gst:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_analytics_common_xeon_gst:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_certificate:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/smtc_common:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/ubuntu:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/busybox:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/xeon-ubuntu1804-service-owt:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/xeon-ubuntu1804-analytics-gst:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/xeon-centos7-media-nginx:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/xeon-centos7-media-ffmpeg:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/xeon-ubuntu1804-media-srs:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/centos:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
# docker save aividtech/elasticsearch-oss:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no" root@$1 "docker load"
docker save aividtech/eclipse-mosquitto:2.0 | sshpass -p $2 ssh -y -o "StrictHostKeyChecking no"  root@$1 "docker load"
