apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    nodePort: 32000
  selector:
    app: kibana
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: CLUSTER_NAME
            value: escluster
          - name: XPACK_SECURITY_ENABLED
            value: "true"
          - name: XPACK_GRAPH_ENABLED
            value: "true"
          - name: XPACK_ML_ENABLED
            value: "true"
          - name: XPACK_REPORTING_ENABLED
            value: "true"
          - name: ELASTICSEARCH_HOSTS
            value: http://db-service:9200

        ports:
        - containerPort: 5601

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
spec:
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
  selector:
    app: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        database: "yes"
    spec:
      enableServiceLinks: true
      imagePullSecrets:
      - name: aividtechvision
      containers:
        - name: db
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: "discovery.type"
              value: "single-node"
      #      - name: "action.auto_create_index"
      #        value: "0"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
#            - mountPath: /usr/share/elasticsearch/data
#              name: elasticdata 
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      initContainers:
        - name: init-volume-sysctl
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sh","-c","sysctl -w vm.max_map_count=262144 && ulimit -n 65535 && ulimit -u 4096"]
          securityContext:
            privileged: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File



