
apiVersion: v1
kind: Service
metadata:
  name: db-service-new
  labels:
    app: db-new
spec:
  clusterIP: None
  ports:
  - port: 9201
    protocol: TCP
  selector:
    app: db-new

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-new
spec:
  serviceName: db-new
  replicas: 1
  selector:
    matchLabels:
      app: db-new
  template:
    metadata:
      labels:
        app: db-new
        database: "yes"
    spec:
      enableServiceLinks: true
      imagePullSecrets:
      - name: aividtechvision
      containers:
        - name: db-new
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: "discovery.type"
              value: "single-node"
      #      - name: "action.auto_create_index"
      #        value: "0"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
            - mountPath: /usr/share/elasticsearch/data
              name: elasticdatanew 
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      initContainers:
        - name: init-volume-sysctl
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sh","-c","sysctl -w vm.max_map_count=262144 && ulimit -n 65535 && ulimit -u 4096"]
          securityContext:
            privileged: true
        - image: busybox:latest
          imagePullPolicy: IfNotPresent
          name: init
          command: ["/bin/chown","0:0","/usr/share/elasticsearch/data"]
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticdatanew
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
          - name: elasticdatanew
            persistentVolumeClaim:
              claimName: elasticdatanew
