apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"db-new"},"name":"db-service-exposed-new","namespace":"default"},"spec":{"ports":[{"port":9201,"protocol":"TCP","targetPort":9201}],"selector":{"app":"db-new"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-03-11T05:39:23Z"
  labels:
    app: db-new
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9201,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-11T05:39:23Z"
  name: db-service-exposed-new
  namespace: default
  resourceVersion: "3486900"
  selfLink: /api/v1/namespaces/default/services/db-service-exposed-new
  uid: 181611d8-9b2f-4e68-bee2-0ec7f1bd9c65
spec:
  clusterIP: 10.108.227.48
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32569
    port: 9201
    protocol: TCP
    targetPort: 9200
  selector:
    app: db-new
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}


