apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: default
  labels:
    app: node-api
spec:
  ports:
  - port: 4003
    nodePort: 32000
  selector:
    app: node-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: default
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: node-api
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 4003
